name: fanfiction-nlp
channels:
  - huggingface
dependencies:
  - scipy
  - pandas
  - scikit-learn
  - nltk
  - spacy
  - inflect
  - pytorch
  - transformers
  - pip
  - pip:
    - benepar
    - pyhocon
